# These are supported funding model platforms

github: [muthuri-dev] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: muthuri-dev # Replace with a single Patreon username
tidelift: npm/babel
custom: ["https://www.paypal.me/kennedy muthuri"]
